export enum Category {
  COURSES = 'COURSES',
  RESTAURANTS = 'RESTAURANTS',
  TRANSPORT = 'TRANSPORT',
  ABONNEMENTS = 'ABONNEMENTS',
  SANTE = 'SANTE',
  LOGEMENT = 'LOGEMENT',
  LOISIRS = 'LOISIRS',
  REVENUS = 'REVENUS',
  BANQUE = 'BANQUE',
  AUTRES = 'AUTRES',
}
