import { Category } from '../models/category.enum';

export const CATEGORY_RULES: Record<Category, string[]> = {
  [Category.COURSES]: [
    'carrefour',
    'leclerc',
    'auchan',
    'lidl',
    'intermarche',
    'monoprix',
    'franprix',
    'casino',
    'super u',
    'hyper u',
    'picard',
    'biocoop',
    'naturalia',
  ],
  [Category.RESTAURANTS]: [
    'mcdonald',
    'mcdo',
    'burger king',
    'kfc',
    'subway',
    'domino',
    'pizza',
    'restaurant',
    'brasserie',
    'cafe',
    'starbucks',
    'sushi',
    'kebab',
    'deliveroo',
    'uber eats',
  ],
  [Category.TRANSPORT]: [
    'total',
    'shell',
    'bp ',
    'esso',
    'station',
    'essence',
    'carburant',
    'sncf',
    'ratp',
    'navigo',
    'peage',
    'autoroute',
    'parking',
    'uber',
    'bolt',
    'blablacar',
  ],
  [Category.ABONNEMENTS]: [
    'netflix',
    'spotify',
    'amazon prime',
    'disney',
    'canal',
    'orange',
    'sfr',
    'bouygues',
    'free mobile',
    'sosh',
    'deezer',
    'apple',
    'google',
    'playstation',
    'xbox',
  ],
  [Category.SANTE]: [
    'pharmacie',
    'medecin',
    'docteur',
    'hopital',
    'clinique',
    'laboratoire',
    'dentiste',
    'ophtalmo',
    'kine',
    'mutuelle',
    'cpam',
    'ameli',
  ],
  [Category.LOGEMENT]: [
    'loyer',
    'edf',
    'engie',
    'gdf',
    'veolia',
    'eau',
    'electricite',
    'gaz',
    'assurance habitation',
    'syndic',
    'charges',
  ],
  [Category.LOISIRS]: [
    'cinema',
    'ugc',
    'pathe',
    'gaumont',
    'fnac',
    'cultura',
    'decathlon',
    'sport',
    'fitness',
    'basic fit',
    'concert',
    'theatre',
    'musee',
    'bowling',
  ],
  [Category.REVENUS]: [
    'salaire',
    'virement recu',
    'vir recu',
    'remboursement',
    'allocation',
    'caf',
    'pole emploi',
    'indemnite',
  ],
  [Category.BANQUE]: [
    'frais bancaire',
    'agios',
    'commission',
    'cotisation carte',
    'assurance carte',
    'interet',
  ],
  [Category.AUTRES]: [],
};
